package com.cyb.blog.service;

import com.cyb.blog.domain.Fabulous;
import com.cyb.blog.domain.FabulousExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FabulousServices {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabulous
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    long countByExample(FabulousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabulous
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    int deleteByExample(FabulousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabulous
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabulous
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    int insert(Fabulous record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabulous
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    int insertSelective(Fabulous record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabulous
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    List<Fabulous> selectByExample(FabulousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabulous
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    Fabulous selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabulous
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") Fabulous record, @Param("example") FabulousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabulous
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    int updateByExample(@Param("record") Fabulous record, @Param("example") FabulousExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabulous
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    int updateByPrimaryKeySelective(Fabulous record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fabulous
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    int updateByPrimaryKey(Fabulous record);
}