package com.cyb.blog.service;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import com.cyb.blog.domain.Blog;
import com.cyb.blog.domain.Reading;
import com.cyb.blog.domain.ReadingExample;
import com.cyb.blog.entity.Pagenation;

public interface ReadingServices {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    long countByExample(ReadingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    int deleteByExample(ReadingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    int insert(Reading record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    int insertSelective(Reading record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    List<Reading> selectByExample(ReadingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    Reading selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") Reading record, @Param("example") ReadingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    int updateByExample(@Param("record") Reading record, @Param("example") ReadingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    int updateByPrimaryKeySelective(Reading record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    int updateByPrimaryKey(Reading record);
    
    public Pagenation getList(Reading reading, Pagenation pagenation);
}