package com.cyb.blog.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    protected List<CriteriaComment> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public CommentExample() {
        oredCriteria = new ArrayList<CriteriaComment>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public List<CriteriaComment> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void or(CriteriaComment criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public CriteriaComment or() {
        CriteriaComment criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public CriteriaComment createCriteria() {
        CriteriaComment criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    protected CriteriaComment createCriteriaInternal() {
        CriteriaComment criteria = new CriteriaComment();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public CriteriaComment andIdIsNull() {
            addCriterion("id is null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdIsNotNull() {
            addCriterion("id is not null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdIsNull() {
            addCriterion("blog_id is null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdIsNotNull() {
            addCriterion("blog_id is not null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdEqualTo(String value) {
            addCriterion("blog_id =", value, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdNotEqualTo(String value) {
            addCriterion("blog_id <>", value, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdGreaterThan(String value) {
            addCriterion("blog_id >", value, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdGreaterThanOrEqualTo(String value) {
            addCriterion("blog_id >=", value, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdLessThan(String value) {
            addCriterion("blog_id <", value, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdLessThanOrEqualTo(String value) {
            addCriterion("blog_id <=", value, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdLike(String value) {
            addCriterion("blog_id like", value, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdNotLike(String value) {
            addCriterion("blog_id not like", value, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdIn(List<String> values) {
            addCriterion("blog_id in", values, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdNotIn(List<String> values) {
            addCriterion("blog_id not in", values, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdBetween(String value1, String value2) {
            addCriterion("blog_id between", value1, value2, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andBlogIdNotBetween(String value1, String value2) {
            addCriterion("blog_id not between", value1, value2, "blogId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdIsNull() {
            addCriterion("user_id is null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountIsNull() {
            addCriterion("comment_count is null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountIsNotNull() {
            addCriterion("comment_count is not null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountEqualTo(Integer value) {
            addCriterion("comment_count =", value, "commentCount");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountNotEqualTo(Integer value) {
            addCriterion("comment_count <>", value, "commentCount");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountGreaterThan(Integer value) {
            addCriterion("comment_count >", value, "commentCount");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("comment_count >=", value, "commentCount");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountLessThan(Integer value) {
            addCriterion("comment_count <", value, "commentCount");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountLessThanOrEqualTo(Integer value) {
            addCriterion("comment_count <=", value, "commentCount");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountIn(List<Integer> values) {
            addCriterion("comment_count in", values, "commentCount");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountNotIn(List<Integer> values) {
            addCriterion("comment_count not in", values, "commentCount");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountBetween(Integer value1, Integer value2) {
            addCriterion("comment_count between", value1, value2, "commentCount");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentCountNotBetween(Integer value1, Integer value2) {
            addCriterion("comment_count not between", value1, value2, "commentCount");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintIsNull() {
            addCriterion("comment_containt is null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintIsNotNull() {
            addCriterion("comment_containt is not null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintEqualTo(String value) {
            addCriterion("comment_containt =", value, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintNotEqualTo(String value) {
            addCriterion("comment_containt <>", value, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintGreaterThan(String value) {
            addCriterion("comment_containt >", value, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintGreaterThanOrEqualTo(String value) {
            addCriterion("comment_containt >=", value, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintLessThan(String value) {
            addCriterion("comment_containt <", value, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintLessThanOrEqualTo(String value) {
            addCriterion("comment_containt <=", value, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintLike(String value) {
            addCriterion("comment_containt like", value, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintNotLike(String value) {
            addCriterion("comment_containt not like", value, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintIn(List<String> values) {
            addCriterion("comment_containt in", values, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintNotIn(List<String> values) {
            addCriterion("comment_containt not in", values, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintBetween(String value1, String value2) {
            addCriterion("comment_containt between", value1, value2, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentContaintNotBetween(String value1, String value2) {
            addCriterion("comment_containt not between", value1, value2, "commentContaint");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateIsNull() {
            addCriterion("comment_date is null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateIsNotNull() {
            addCriterion("comment_date is not null");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateEqualTo(Date value) {
            addCriterion("comment_date =", value, "commentDate");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateNotEqualTo(Date value) {
            addCriterion("comment_date <>", value, "commentDate");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateGreaterThan(Date value) {
            addCriterion("comment_date >", value, "commentDate");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateGreaterThanOrEqualTo(Date value) {
            addCriterion("comment_date >=", value, "commentDate");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateLessThan(Date value) {
            addCriterion("comment_date <", value, "commentDate");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateLessThanOrEqualTo(Date value) {
            addCriterion("comment_date <=", value, "commentDate");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateIn(List<Date> values) {
            addCriterion("comment_date in", values, "commentDate");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateNotIn(List<Date> values) {
            addCriterion("comment_date not in", values, "commentDate");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateBetween(Date value1, Date value2) {
            addCriterion("comment_date between", value1, value2, "commentDate");
            return (CriteriaComment) this;
        }

        public CriteriaComment andCommentDateNotBetween(Date value1, Date value2) {
            addCriterion("comment_date not between", value1, value2, "commentDate");
            return (CriteriaComment) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 27 13:11:27 CST 2019
     */
    public static class CriteriaComment extends GeneratedCriteria {

        protected CriteriaComment() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}