package com.cyb.blog.domain;

import java.util.Date;

public class Fabulous {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabulous.id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabulous.blog_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    private String blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabulous.user_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabulous.fabulous_count
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    private Integer fabulousCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fabulous.fabulous_date
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    private Date fabulousDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabulous.id
     *
     * @return the value of fabulous.id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabulous.id
     *
     * @param id the value for fabulous.id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabulous.blog_id
     *
     * @return the value of fabulous.blog_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabulous.blog_id
     *
     * @param blogId the value for fabulous.blog_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabulous.user_id
     *
     * @return the value of fabulous.user_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabulous.user_id
     *
     * @param userId the value for fabulous.user_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabulous.fabulous_count
     *
     * @return the value of fabulous.fabulous_count
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public Integer getFabulousCount() {
        return fabulousCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabulous.fabulous_count
     *
     * @param fabulousCount the value for fabulous.fabulous_count
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setFabulousCount(Integer fabulousCount) {
        this.fabulousCount = fabulousCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fabulous.fabulous_date
     *
     * @return the value of fabulous.fabulous_date
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public Date getFabulousDate() {
        return fabulousDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fabulous.fabulous_date
     *
     * @param fabulousDate the value for fabulous.fabulous_date
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setFabulousDate(Date fabulousDate) {
        this.fabulousDate = fabulousDate;
    }
}