package com.cyb.blog.domain;

import java.util.Date;

public class Foward {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foward.id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foward.blog_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    private String blogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foward.user_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foward.forward_count
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    private Integer forwardCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foward.foward_containt
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    private String fowardContaint;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column foward.foward_date
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    private Date fowardDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foward.id
     *
     * @return the value of foward.id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foward.id
     *
     * @param id the value for foward.id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foward.blog_id
     *
     * @return the value of foward.blog_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public String getBlogId() {
        return blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foward.blog_id
     *
     * @param blogId the value for foward.blog_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setBlogId(String blogId) {
        this.blogId = blogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foward.user_id
     *
     * @return the value of foward.user_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foward.user_id
     *
     * @param userId the value for foward.user_id
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foward.forward_count
     *
     * @return the value of foward.forward_count
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public Integer getForwardCount() {
        return forwardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foward.forward_count
     *
     * @param forwardCount the value for foward.forward_count
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setForwardCount(Integer forwardCount) {
        this.forwardCount = forwardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foward.foward_containt
     *
     * @return the value of foward.foward_containt
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public String getFowardContaint() {
        return fowardContaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foward.foward_containt
     *
     * @param fowardContaint the value for foward.foward_containt
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setFowardContaint(String fowardContaint) {
        this.fowardContaint = fowardContaint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column foward.foward_date
     *
     * @return the value of foward.foward_date
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public Date getFowardDate() {
        return fowardDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column foward.foward_date
     *
     * @param fowardDate the value for foward.foward_date
     *
     * @mbg.generated Sun Jan 27 13:11:27 CST 2019
     */
    public void setFowardDate(Date fowardDate) {
        this.fowardDate = fowardDate;
    }
}