package com.cyb.blog.domain;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.id
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.author
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.createtime
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.message
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column message.image
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.id
     *
     * @return the value of message.id
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.id
     *
     * @param id the value for message.id
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.author
     *
     * @return the value of message.author
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.author
     *
     * @param author the value for message.author
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.createtime
     *
     * @return the value of message.createtime
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.createtime
     *
     * @param createtime the value for message.createtime
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.message
     *
     * @return the value of message.message
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.message
     *
     * @param message the value for message.message
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column message.image
     *
     * @return the value of message.image
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column message.image
     *
     * @param image the value for message.image
     *
     * @mbg.generated Sat Feb 09 22:12:05 CST 2019
     */
    public void setImage(String image) {
        this.image = image;
    }
}