package com.cyb.blog.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.cyb.blog.entity.Pagenation;

public class ReadingExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    protected List<CriteriaReading> oredCriteria;
    
    protected Pagenation pagenation;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    public ReadingExample() {
        oredCriteria = new ArrayList<CriteriaReading>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    public List<CriteriaReading> getOredCriteria() {
        return oredCriteria;
    }
    
    public Pagenation getPagenation() {
		return pagenation;
	}

	public void setPagenation(Pagenation pagenation) {
		this.pagenation = pagenation;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    public void or(CriteriaReading criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    public CriteriaReading or() {
        CriteriaReading criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    public CriteriaReading createCriteria() {
        CriteriaReading criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    protected CriteriaReading createCriteriaInternal() {
        CriteriaReading criteria = new CriteriaReading();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public CriteriaReading andIdIsNull() {
            addCriterion("id is null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdIsNotNull() {
            addCriterion("id is not null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleIsNull() {
            addCriterion("title is null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleIsNotNull() {
            addCriterion("title is not null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorIsNull() {
            addCriterion("author is null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (CriteriaReading) this;
        }

        public CriteriaReading andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendIsNull() {
            addCriterion("recommend is null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendIsNotNull() {
            addCriterion("recommend is not null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendEqualTo(String value) {
            addCriterion("recommend =", value, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendNotEqualTo(String value) {
            addCriterion("recommend <>", value, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendGreaterThan(String value) {
            addCriterion("recommend >", value, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendGreaterThanOrEqualTo(String value) {
            addCriterion("recommend >=", value, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendLessThan(String value) {
            addCriterion("recommend <", value, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendLessThanOrEqualTo(String value) {
            addCriterion("recommend <=", value, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendLike(String value) {
            addCriterion("recommend like", value, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendNotLike(String value) {
            addCriterion("recommend not like", value, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendIn(List<String> values) {
            addCriterion("recommend in", values, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendNotIn(List<String> values) {
            addCriterion("recommend not in", values, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendBetween(String value1, String value2) {
            addCriterion("recommend between", value1, value2, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andRecommendNotBetween(String value1, String value2) {
            addCriterion("recommend not between", value1, value2, "recommend");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageIsNull() {
            addCriterion("image is null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageIsNotNull() {
            addCriterion("image is not null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageEqualTo(String value) {
            addCriterion("image =", value, "image");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageNotEqualTo(String value) {
            addCriterion("image <>", value, "image");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageGreaterThan(String value) {
            addCriterion("image >", value, "image");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageGreaterThanOrEqualTo(String value) {
            addCriterion("image >=", value, "image");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageLessThan(String value) {
            addCriterion("image <", value, "image");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageLessThanOrEqualTo(String value) {
            addCriterion("image <=", value, "image");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageLike(String value) {
            addCriterion("image like", value, "image");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageNotLike(String value) {
            addCriterion("image not like", value, "image");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageIn(List<String> values) {
            addCriterion("image in", values, "image");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageNotIn(List<String> values) {
            addCriterion("image not in", values, "image");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageBetween(String value1, String value2) {
            addCriterion("image between", value1, value2, "image");
            return (CriteriaReading) this;
        }

        public CriteriaReading andImageNotBetween(String value1, String value2) {
            addCriterion("image not between", value1, value2, "image");
            return (CriteriaReading) this;
        }
        
        public CriteriaReading andModalIsNull() {
            addCriterion("modal is null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalIsNotNull() {
            addCriterion("modal is not null");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalEqualTo(String value) {
            addCriterion("modal =", value, "modal");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalNotEqualTo(String value) {
            addCriterion("modal <>", value, "modal");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalGreaterThan(String value) {
            addCriterion("modal >", value, "modal");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalGreaterThanOrEqualTo(String value) {
            addCriterion("modal >=", value, "modal");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalLessThan(String value) {
            addCriterion("modal <", value, "modal");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalLessThanOrEqualTo(String value) {
            addCriterion("modal <=", value, "modal");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalLike(String value) {
            addCriterion("modal like", value, "modal");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalNotLike(String value) {
            addCriterion("modal not like", value, "modal");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalIn(List<String> values) {
            addCriterion("modal in", values, "modal");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalNotIn(List<String> values) {
            addCriterion("modal not in", values, "modal");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalBetween(String value1, String value2) {
            addCriterion("modal between", value1, value2, "modal");
            return (CriteriaReading) this;
        }

        public CriteriaReading andModalNotBetween(String value1, String value2) {
            addCriterion("modal not between", value1, value2, "modal");
            return (CriteriaReading) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reading
     *
     * @mbg.generated do_not_delete_during_merge Mon Feb 04 09:10:23 CST 2019
     */
    public static class CriteriaReading extends GeneratedCriteria {

        protected CriteriaReading() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table reading
     *
     * @mbg.generated Mon Feb 04 09:10:23 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}